### ISSUE TITLE
Keep plugin.info.txt up to date

### ISSUE THREAD

**Issue by tormec** [parmaja/pglist#2]
Hi,
Please, keep up to date the `plugin.info.txt` file and the `lastupdate` field in your DokuWiki page: they must have the same date otherwise in Extension Manager there will be always a notify message for a new version available.

Now you have:
(in your DokuWiki page)    `lastupdate : 2013-07-20`
(in your plugin.info.txt)  `date 2012-06-04`

They should be (It seems to me that the last release is 2014-01-08):
(in your DokuWiki page)     `lastupdate : 2014-01-08`
(in your plugin.info.txt)   `date 2014-01-08`

See the note at the bottom of this page https://www.dokuwiki.org/devel:plugin_info

Thanks

**Comment by zaher** [comment]
I will do my best, thank you :)
