### ISSUE TITLE
Attempted installation fails

### ISSUE THREAD

**Issue by suedunham** [parmaja/pglist#5]
When trying to install this plugin into the newest Hogfather version of DokuWiki, I get the following message for every page of the wiki:

Fatal error: Declaration of action_plugin_pglist::register(&$controller) must be compatible with dokuwiki\Extension\ActionPlugin::register(Doku_Event_Handler $controller) in C:\path-to-wiki\lib\plugins\pglist\action.php on line 17

Deleting the folder makes it go away, but, obviously, I haven't been able to try the plugin.

**Comment by zaher** [comment]
Done, Thank you :)
